### PR TITLE
Simplify seed project installation with Dockerfile option

### PR DESCRIPTION
**Pull request by jamesbyars**

### CODE REVIEW

**Comment by gdi2290** [comment]
why have package.json in `config/`?

**Comment by jamesbyars** [comment]
When running in a container you have to bind the host to 0.0.0.0.

**Comment by pkozlowski-opensource** [comment]
Honestly I would prefer that we keep docker out of this seed. It is meant to be a simple (or simplest possible) and I would like it to stay this way. There are many other elaborate starter kits where docker option might makes sense.

All it to say that I would for _not_ merging this PR.

**Comment by jamesbyars** [comment]
I understand your concern.  I created it because I had trouble getting the seed project running on my mac and I thought it may help others.  I've seen other projects offer two types of installation instructions (see the updates to README.md) and I thought that pattern would apply to this.  People running the seed project can choose to run with the standard installation instructions or, if they find it easier, leverage Docker.

**Comment by gdi2290** [comment]
I don't like having two `package.json`s to manage

**Pull request closed without merging**
