### PR TITLE
update to angular2 beta12 + fix

### PR DESCRIPTION
**Pull request by toutpt**
Just and update to make it works with last beta.

### CODE REVIEW

**Comment by toutpt** [comment]
I signed it!

**Comment by gdi2290** [comment]
thanks! Although, it seems like you have an old fork of the repo. The latest version has been updated to angular2 beta.12 if you can pull down the latest changes and try for yourself.

**Comment by toutpt** [comment]
@gdi2290 Are you sure, I have just cloned it before this commit. I believe you are looking the master branch instead of the systemjs branch.

**Comment by gdi2290** [comment]
oops, you're right sorry

**Pull request merged**
