### PR TITLE
updates to newest angular 2

### PR DESCRIPTION
**Pull request by Ibrahim-Islam**
Updates Angular 2 and its dependencies to newest versions

### CODE REVIEW

**Comment by Ibrahim-Islam** [comment]
I signed it!

**Comment by gdi2290** [comment]
can you pull latest next time. the repo was already updated

**Comment by gdi2290** [comment]
nvm I forgot to push up those changes :/

**Comment by gdi2290** [comment]
oh oops I keep forgetting there are two branches

**Pull request merged**
