### PR TITLE
SystemJS + Beta 0

### PR DESCRIPTION
**Pull request by robwormald**

### CODE REVIEW

**Comment by cebor** [comment]
:+1:

**Comment by Foxandxss** [comment]
Sounds good to me Rob.

**Comment by shidhincr** [comment]
Switching from webpack to SystemJS ? or both will be supported ?

**Comment by Foxandxss** [comment]
Switching indeed. This is just a demo project, not a project to clone for all your new applications.

That is what `angular-cli` is for :)

**Comment by shidhincr** [comment]
Thanks @Foxandxss. Will try `angular-cli`

**Comment by robwormald** [comment]
fyi, keeping the webpack build for the moment, gonna push this branch to the systemjs branch.

**Pull request closed without merging**
